version: '3.4'

services:
  example:
    image: ${DOCKER_REGISTRY-}example
    depends_on:
      - taos 
    links:
      - taos 

    build:
      context: .
      dockerfile: src/Example/Dockerfile
    networks:
      - taos-network

  taos:
    image: tdengine/tdengine:3.0.4.1
    restart: always
    hostname: taos
    ports:
      - 6030:6030
      - 6035:6035
      - 6041:6041
      - 6030-6040:6030-6040/udp
    networks:
      - taos-network

networks: 
  taos-network:
      driver:  bridge
